### ISSUE TITLE
can you please tell me what javafx version you were using?

### ISSUE THREAD

**Issue by ShallJaiden** [hanshsieh/pixivj-jfx#11]
it gave me this exception
```
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.sg.prism.web.NGWebView (in unnamed module @0x5f64ef6d) cannot access class com.sun.javafx.sg.prism.NGGroup (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.sg.prism to unnamed module @0x5f64ef6d
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.github.hanshsieh.pixivjjfx.stage.PixivLoginStage$Builder.buildInFxThread(PixivLoginStage.java:103)
	at Test.lambda$start$0(Test.java:23)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.sg.prism.web.NGWebView (in unnamed module @0x5f64ef6d) cannot access class com.sun.javafx.sg.prism.NGGroup (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.sg.prism to unnamed module @0x5f64ef6d
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.github.hanshsieh.pixivjjfx.stage.PixivLoginStage.<init>(PixivLoginStage.java:143)
	at com.github.hanshsieh.pixivjjfx.stage.PixivLoginStage$Builder.build(PixivLoginStage.java:87)
	at com.github.hanshsieh.pixivjjfx.stage.PixivLoginStage$Builder.lambda$buildInFxThread$0(PixivLoginStage.java:102)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
```

**Comment by hanshsieh** [comment]
I'm using OpenJFX 15.0.1 as indicated [here](https://github.com/hanshsieh/pixivj-jfx/blob/7033c80af5865c711f571126521d99d8cb08e87f/pom.xml#L46).  
Does your project use Java module? I guess the problem is related to that.
If you don't define `module-info.java`, your project will by default be an unnamed module.
I found [this article](https://stackoverflow.com/questions/54824108/superclass-access-check-failed-class-com-sun-javafx-sg-prism-web-ngwebview). You can try to add `--add-exports javafx.graphics/com.sun.javafx.sg.prism=ALL-UNNAMED` to your `javac`. For maven, you can add the options as show [here](https://stackoverflow.com/a/68058292/7807179).  
However, I would suggest you use the Java module if you haven't. I have another [integration test repo](https://github.com/hanshsieh/pixivj-int), and it doesn't have the problem.  
Let me know if it solves your problem.  
If not, maybe you can tell me your environment, e.g. Java version? Java SE or Java EE? Windows or Unix?
